### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by KrypticCoconut** [beboxos/P4wnP1_ALOA_OLED_MENU_V2#7]
in the install.sh there are messed up paths

**Comment by KrypticCoconut** [comment]
i keep getting this error 
Traceback (most recent call last):
  File "/root/BeBoXGui/gui.py", line 3, in <module>
    from luma.core.interface.serial import i2c, spi
ImportError: No module named luma.core.interface.serial

@beboxos can you help?

**Comment by beboxos** [comment]
connect you pi to internet (wifi ...) , connect to you pi and install modules

pip install luma.core
pip install luma.oled

don't forget to set on /boot/config.txt

spi and or i2c (depends on your oled) on to activate it on pi

**Comment by KrypticCoconut** [comment]
Now it error 
Traceback (most recent call last):
  File "/root/BeBoXGui/gui.py", line 19, in <module>
    import smbus
ImportError: No module named smbus

I then pip install smbus and then it gave this error
Traceback (most recent call last):
  File "/root/BeBoXGui/gui.py", line 42, in <module>
    bus = smbus.SMBus(1)  # 0 = /dev/i2c-0 (port I2C0), 1 = /dev/i2c-1 (port I2C1)
IOError: [Errno 2] No such file or directory

Im not able to get this working @beboxos  :[

**Comment by KrypticCoconut** [comment]
and it keeps giving me errors python 2.7 has reached the end of its life

**Comment by beboxos** [comment]
Use pip3 instead my menu work with python3

Le jeu. 20 févr. 2020 à 16:34, KrypticCoconut <notifications@github.com> a
écrit :

**Comment by beboxos** [comment]
i've tried pip3 install luma.core and same error 

what funcking idea have they had to stop python 2 support , when all drivers don't work with pyhon3 :'(

i have no idea how to get it work on last version of P4wnP1

(i have sme type of problem trying to make it works with an LCD, driver is python2 only)

**Comment by KrypticCoconut** [comment]
Definitely do feel you man, will it work on p4wnp1 alpha2?

**Comment by beboxos** [comment]
https://twitter.com/BeBoXoS/status/1230635682986700800

see my last tweet , yes i'm working on it , somes things to fix but it's working

installing luma.core etc was a real pain fixing dependencies etc .. but after 2 hours it's working

**Comment by KrypticCoconut** [comment]
wait so it works on p4wn alpha but ur working to get it it work on the beta ? 
im going to get a copy of alpha and try it on that, in which folder can i clone the git repo?
Edit: doesnt seem to work on prev p4wnp1 ver too :[

**Comment by KrypticCoconut** [comment]
I downloaded ur pre installed img and shoudl i say that im so impressed, tho i should say that the as i click on system info the oled shuts down

**Comment by beboxos** [comment]
https://mega.nz/#!YYtS2S6A!Q5OgMvLUtAM_x7jt7vBTY8Zu8lHdyyPoaLdsipVufWg 

last P4wnP1 v0.1.1 with oled menu , drivers ... on it

enjoy

**Comment by beboxos** [comment]
for you system info on "old" img , edit gui.py to put UPS=0 (as i explain on the readme.txt with the image)

**Comment by MiguelBits** [comment]
hey , downloaded both versions, the one on mega and the one in alpha version, both always come down to this error
 File "/root/BeBoXGui/gui.py", line 42, in
bus = smbus.SMBus(1) # 0 = /dev/i2c-0 (port I2C0), 1 = /dev/i2c-1 (port I2C1)
IOError: [Errno 2] No such file or directory
I read all this post btw...
any sugestions ?

**Comment by MiguelBits** [comment]
so I fixed all the above problems, "import smbus" needed to be "import smbus2 as smbus"
made UPS = 0
I have the same OLED display as you but it only blinks white light
PS: i commented out bus = smbus.SMBus(1) # 0 = /dev/i2c-0 (port I2C0), 1 = /dev/i2c-1 (port I2C1) as it still gives error, I am using SPI not I2C so why use it ?

**Comment by MasterInNursery** [comment]
very nice project but I get a little bit problems, i changed ups = 0 and also commented out bus = smbus.SMBus(1). when i click on systrm info, it will get me the following error.

**Traceback (most recent call last):
  File "gui.py", line 1105, in <module>
    sysinfos()
  File "gui.py", line 210, in sysinfos
    IP2 = subprocess.check_output(cmd, shell = True ).split(" ")[1]
TypeError: a bytes-like object is required, not 'str'**
by the way, i am use python3 to run this gui.py since use python 2 returns me an error of **No module named luma.core.interface.serial**

could you help me with this problem? thanks so much @beboxos

**Comment by FuocomanSap** [comment]
Same as @MasterInNursery

**Comment by FuocomanSap** [comment]
> Same as @MasterInNursery

OK, solved.
I've posted a pull request, now the fork supports python3.7.

**Comment by joshdyod** [comment]
Sounds like same problem as [MiguelBits](https://github.com/MiguelBits) White screen just blinking, set UPS = 0  using  the latest .img file with recommended waveshare hat. 
When I run python runmenu.py I do get a message saying 
no pid
